openapi: 3.0.0
info:
  title: Cat Facts API
  version: '1.0'
  description: Cat Facts tool to learn about cats.
servers:
  - url: https://devhub-ijf3pf6xya-uc.a.run.app
paths:
  /breeds:
    get:
      tags:
      - Breeds
      summary: Get a list of breeds
      description: Returns a a list of breeds
      operationId: getBreeds
      parameters:
      - name: limit
        in: query
        description: limit the amount of results returned
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Breed"
  /fact:
    get:
      tags:
      - Facts
      summary: Get Random Fact
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
      - name: max_length
        in: query
        description: maximum length of returned fact
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CatFact"
        '404':
          description: Fact not found
  /facts:
    get:
      tags:
      - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
      - name: max_length
        in: query
        description: maximum length of returned fact
        required: false
        schema:
          type: integer
          format: int64
      - name: limit
        in: query
        description: limit the amount of results returned
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/CatFact"
  /runtimes:
    get:
      tags:
      - Runtimes
      summary: Get a list of runtimes
      description: Returns a a list of runtimes
      operationId: getRuntimes
      parameters:
      - name: artufacts
        in: query
        description: match artifacts
        required: false
        schema:
          type: string
          format: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Runtime"                  
  /vulnerabilities:
    get:
      tags:
      - Vulnerabilities
      summary: Get a list of vulnerabilities
      description: Returns a a list of vulnerabilities
      operationId: getVulnerabilities
      parameters:
      - name: vulnerability
        in: query
        description: filter by vulnerability
        required: false
        schema:
          type: string
          format: string
      - name: max_length
        in: query
        description: maximum length of returned fact
        required: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Vulnerability"
  /vulnerable-artifacts:
    get:
      tags:
      - VulnerableArtifacts
      summary: Get a list of vulnerable artifacts
      description: Returns a a list of vulnerable artifacts
      operationId: getVulnerableArtifacts
      parameters:
      - name: vulnerability
        in: query
        description: filter by vulnerability
        required: false
        schema:
          type: string
          format: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                title: Artifacts
                description: Artifacts
                type: array
                items:
                  type: string
                  format: string                  
components:
  schemas:
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    CatFact:
      title: CatFact model
      description: CatFact
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
    Runtime:
      title: Runtime model
      description: Runtime
      properties:
        serviceName:
          title: ServiceName
          description: ServiceName
          type: string
          format: string
        revisionName:
          title: RevisionName
          description: RevisionName
          type: string
          format: string
        artifactUri:
          title: ArtifactURI
          description: ArtifactURI
          type: string
          format: string
        match:
          title: Match
          description: Match
          type: boolean
      type: object
    Vulnerability:
      title: Vulnerability model
      description: Vulnerability
      properties:
        cve:
          title: Cve
          description: Cve
          type: string
          format: string
        severity:
          title: Severity
          description: Severity
          type: string
          format: string
        cvss:
          title: Cvss
          description: Cvss
          type: number
          format: float
        artifactUri:
          title: ArtifactURI
          description: ArtifactURI
          type: string
          format: string
      type: object